global using System.IO;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Media;
global using System.Windows.Input;
global using Application = System.Windows.Application;
global using Button = System.Windows.Controls.Button;
global using TextBox = System.Windows.Controls.TextBox;
global using CheckBox = System.Windows.Controls.CheckBox;
global using ComboBox = System.Windows.Controls.ComboBox;
global using Orientation = System.Windows.Controls.Orientation;
global using HorizontalAlignment = System.Windows.HorizontalAlignment;
global using VerticalAlignment = System.Windows.VerticalAlignment;
global using Color = System.Windows.Media.Color;
global using Brushes = System.Windows.Media.Brushes;
global using Point = System.Windows.Point;
global using Size = System.Windows.Size;
global using Rectangle = System.Windows.Shapes.Rectangle;
