using CodexTop.Core;
using System.Text;
using System.Text.Json;

int passed = 0;
var origin = DateTimeOffset.Parse("2026-09-20T00:00:00Z");
byte[] Event(string type, int seconds, string? turn = "A", string? kind = "event_msg", Dictionary<string, object?>? fields = null)
{
    var payload = fields ?? new(); payload["type"] = type; if (turn != null) payload["turn_id"] = turn;
    return Encoding.UTF8.GetBytes(JsonSerializer.Serialize(new { type = kind, timestamp = origin.AddSeconds(seconds).ToString("O"), payload }));
}
void Check(bool condition, string message) { if (!condition) throw new Exception(message); }
void Test(string name, Action test) { test(); passed++; Console.WriteLine($"PASS {name}"); }
RolloutReducer Started() { var r = new RolloutReducer(); r.Consume(Event("task_started", 0)); return r; }
byte[] Call(string name, string id, int second) => Event("function_call", second, null, "response_item", new() { ["name"] = name, ["call_id"] = id });
byte[] Output(string id, int second) => Event("function_call_output", second, null, "response_item", new() { ["call_id"] = id });
CodexTask Task(string id, Phase phase, string? parent = null, int created = 0) => new(id, id, "project", origin.AddSeconds(created), origin, parent, "unused", new() { Phase = phase });
string TempFile(string prefix) { var dir = Path.Combine(Path.GetTempPath(), "CodexTopTests", Guid.NewGuid().ToString("N")); Directory.CreateDirectory(dir); return Path.Combine(dir, prefix); }
void WriteEvents(string path, params byte[][] events) { using var f = File.Create(path); foreach (var e in events) { f.Write(e); f.WriteByte(10); } }
void Append(string path, byte[] item, bool newline = true) { using var f = new FileStream(path, FileMode.Append, FileAccess.Write, FileShare.ReadWrite); f.Write(item); if (newline) f.WriteByte(10); }

Test("explicit start, completion and fresh turn", () => { var r = Started(); r.Consume(Event("task_complete", 5)); Check(r.Activity.Phase == Phase.Completed, "completion"); r.Consume(Event("task_started", 10, "B")); Check(r.Activity.Phase == Phase.Running && r.Activity.StartedAt == origin.AddSeconds(10), "new turn"); });
Test("old turn completion cannot end new turn", () => { var r = Started(); r.Consume(Event("task_started", 10, "B")); r.Consume(Event("task_complete", 20, "A")); Check(r.Activity.Phase == Phase.Running, "stale terminal"); });
Test("out of order events ignored", () => { var r = Started(); r.Consume(Event("task_complete", 10)); r.Consume(Event("task_started", 2)); Check(r.Activity.Phase == Phase.Completed, "time guard"); });
Test("synchronous answers matched by call id", () => { var r = Started(); r.Consume(Call("request_user_input", "one", 2)); r.Consume(Output("wrong", 3)); Check(r.Activity.Phase == Phase.Waiting, "wrong call"); r.Consume(Output("one", 4)); Check(r.Activity.Phase == Phase.Running, "matched answer"); });
Test("multiple questions do not clear each other", () => { var r = Started(); r.Consume(Call("request_user_input", "one", 2)); r.Consume(Call("request_user_input", "two", 3)); r.Consume(Output("one", 4)); Check(r.Activity.Phase == Phase.Waiting, "outstanding question"); r.Consume(Output("two", 5)); Check(r.Activity.Phase == Phase.Running, "all answered"); });
Test("async question survives output and turn completion", () => { var r = Started(); r.Consume(Call("request_user_input_async", "one", 2)); r.Consume(Output("one", 3)); r.Consume(Event("task_complete", 4)); Check(r.Activity.Phase == Phase.Waiting, "async wait"); r.Consume(Event("message", 5, null, "response_item", new() { ["role"] = "user" })); Check(r.Activity.Phase == Phase.Running, "written user reply"); });
Test("mixed async and sync questions", () => { var r = Started(); r.Consume(Call("request_user_input_async", "async", 2)); r.Consume(Call("request_user_input", "sync", 3)); r.Consume(Output("sync", 4)); Check(r.Activity.Phase == Phase.Waiting, "async remains"); });
Test("failure remains after trailing completion and output", () => { var r = Started(); r.Consume(Event("task_failed", 2)); r.Consume(Event("agent_message", 3)); r.Consume(Output("tool", 4)); r.Consume(Event("task_complete", 5)); Check(r.Activity.Phase == Phase.Failed, "failure erased"); r.Consume(Event("user_message", 6)); Check(r.Activity.Phase == Phase.Running, "explicit continuation"); });
Test("waiting duration stays fixed", () => { var r = Started(); r.Consume(Call("request_user_input", "one", 65)); r.Consume(Call("request_user_input", "two", 70)); Check(r.Activity.Timer(origin.AddHours(2)) == "01:05", "waiting clock"); });
Test("missing start is not fabricated", () => { var r = new RolloutReducer(); r.Consume(Event("agent_message", 20)); Check(r.Activity.Timer(origin.AddMinutes(2)) == "--:--", "unknown time"); });
Test("waiting does not expire; running does", () => { var r = Started(); Check(r.Activity.Effective(origin.AddMinutes(16)).Phase == Phase.Unknown, "stale running"); r.Consume(Call("request_user_input", "one", 20)); Check(r.Activity.Effective(origin.AddDays(1)).Phase == Phase.Waiting, "wait expiry"); });
Test("malformed JSON leaves state intact", () => { var r = Started(); r.Consume("{bad json}"u8); Check(r.Activity.Phase == Phase.Running, "invalid JSON"); });
Test("timer recovery requires compatible activity", () => { var r = new RolloutReducer(); r.Consume(Event("agent_message", 20)); var recovered = r.Activity with { StartedAt = origin, TurnId = "A" }; Check(r.RecoverTiming(recovered), "valid recovery"); Check(r.Activity.StartedAt == origin && r.Activity.Phase == Phase.Running, "time only"); var other = new RolloutReducer(); other.Consume(Event("agent_message", 20)); Check(!other.RecoverTiming(recovered with { LastEventAt = origin }), "incompatible recovery"); });
Test("nested child waiting supplies navigation and timer", () => { var root = Task("a", Phase.Running); var child = Task("b", Phase.Completed, "a"); var grandchild = Task("c", Phase.Waiting, "b"); var graph = new TaskGraph([root, child, grandchild]); var row = graph.Row(root); Check(graph.Roots.Count == 1 && row.NavigationTarget.Id == "c" && row.Activity.Phase == Phase.Waiting, "child aggregation"); });
Test("cycle graph resolves deterministically", () => { var graph = new TaskGraph([Task("c", Phase.Running, "b"), Task("b", Phase.Completed, "a"), Task("a", Phase.Waiting, "c")]); Check(graph.Roots.Single().Id == "a" && graph.RootIds.Values.All(id => id == "a"), "cycle"); });
Test("missing parent remains visible", () => { var graph = new TaskGraph([Task("a", Phase.Running, "missing")]); Check(graph.Roots.Count == 1, "orphan"); });
Test("first launch excludes completed history", () => { var p = new Preferences(); var tasks = new[] { Task("a", Phase.Running), Task("b", Phase.Completed) }; MonitoringPolicy.Reconcile(p, tasks, new(tasks), origin); Check(p.SelectedIds.SetEquals(["a"]), "initial selection"); });
Test("same second new task joins but baseline does not", () => { var p = new Preferences(); var old = Task("old", Phase.Completed); MonitoringPolicy.Reconcile(p, [old], new([old]), origin.AddMilliseconds(600)); var newer = Task("new", Phase.Running); MonitoringPolicy.Reconcile(p, [old, newer], new([old, newer]), origin.AddSeconds(2)); Check(p.SelectedIds.SetEquals(["new"]), "same-second policy"); });
Test("manual exclusion wins over automatic", () => { var p = new Preferences { Initialized = true, AutoEnabledAt = origin, ExcludedIds = ["a"] }; var task = Task("a", Phase.Running, created: 2); MonitoringPolicy.Reconcile(p, [task], new([task]), origin.AddSeconds(3)); Check(p.SelectedIds.Count == 0, "excluded task"); });
Test("selection apply preserves newly auto-added tasks", () => { var p = new Preferences { SelectedIds = ["a", "auto"] }; MonitoringPolicy.ApplySelection(p, ["a"], ["b"]); Check(p.SelectedIds.SetEquals(["auto", "b"]) && p.ExcludedIds.Contains("a"), "draft delta"); });
Test("floating returns to previous mode after reload", () => { var p = new Preferences { Placement = Placement.Tray }; p.SetPlacement(Placement.Floating); p.SetPlacement(Placement.Floating); var file = new PreferencesFile(TempFile("settings.json")); file.Save(p); var loaded = file.Load(); Check(loaded.ReturnPlacement == Placement.Tray, "return mode"); });
Test("scale clamps, snaps, rejects nonfinite", () => { Check(Preferences.NormalizeScale(double.NaN) == 1 && Preferences.NormalizeScale(.82) == .8 && Preferences.NormalizeScale(5) == 1.2 && Preferences.NormalizeScale(-1) == .6, "scale"); });
Test("partial line is read only once newline arrives", () => { var path = TempFile("events.jsonl"); WriteEvents(path, Event("task_started", 0)); var reader = new IncrementalRollout(); reader.Refresh(path); Append(path, Event("task_complete", 2), false); reader.Refresh(path); Check(reader.Reducer.Activity.Phase == Phase.Running && reader.PendingBytes > 0, "partial line"); Append(path, [], true); reader.Refresh(path); Check(reader.Reducer.Activity.Phase == Phase.Completed, "completed line"); Check(reader.Refresh(path) == 0, "no reread"); });
Test("incremental budget never skips waiting event", () => { var path = TempFile("events.jsonl"); WriteEvents(path, Event("task_started", 0)); var reader = new IncrementalRollout(); reader.Refresh(path); Append(path, Call("request_user_input_async", "q", 1)); using (var stream = new FileStream(path, FileMode.Append)) { var line = Encoding.UTF8.GetBytes("{\"unknown\":\"" + new string('a', 4000) + "\"}\n"); for (int i = 0; i < 1200; i++) stream.Write(line); } reader.Refresh(path); Check(!reader.CaughtUp, "budget should be exhausted"); reader.Refresh(path); Check(reader.CaughtUp && reader.Reducer.Activity.Phase == Phase.Waiting, "lost waiting event"); });
Test("truncated and replaced files reset state", () => { var path = TempFile("events.jsonl"); WriteEvents(path, Event("task_started", 0), Call("request_user_input_async", "one", 2)); var reader = new IncrementalRollout(); reader.Refresh(path); var replacement = path + ".new"; WriteEvents(replacement, Event("task_started", 10, "B")); File.Move(replacement, path, true); reader.Refresh(path); Check(reader.Reducer.Activity.Phase == Phase.Running && reader.Reducer.Activity.TurnId == "B", "replacement"); });
Test("oversize lines bounded and next record readable", () => { var path = TempFile("events.jsonl"); WriteEvents(path, Event("task_started", 0)); var reader = new IncrementalRollout(); reader.Refresh(path); Append(path, Encoding.UTF8.GetBytes(new string('x', 200000))); Append(path, Event("task_complete", 2)); reader.Refresh(path); Check(reader.PendingBytes <= IncrementalRollout.ChunkSize && reader.Reducer.Activity.Phase == Phase.Completed, "oversize"); });
Test("cold-tail recovery gets explicit start without changing state", () => { var path = TempFile("events.jsonl"); WriteEvents(path, Event("task_started", 0)); for (int i = 0; i < 45; i++) Append(path, Encoding.UTF8.GetBytes("{\"unknown\":\"" + new string('a', 4000) + "\"}")); Append(path, Event("agent_message", 10)); var reader = new IncrementalRollout(); reader.Refresh(path); Check(reader.Reducer.Activity.StartedAt == null, "tail should miss start"); reader.RecoverTiming(path); Check(reader.Reducer.Activity.StartedAt == origin && reader.Reducer.Activity.Phase == Phase.Running, "timing recovery"); });
Test("quota uses current codex bucket and preserves missing window", () => { using var doc = JsonDocument.Parse("""{"rateLimits":{"primary":{"usedPercent":1,"windowDurationMins":300}},"rateLimitsByLimitId":{"codex":{"primary":{"usedPercent":28,"windowDurationMins":300},"secondary":null}}}"""); var q = AccountUsageClient.Parse(doc.RootElement, origin); Check(q.Windows.Count == 1 && q.Windows[0].Remaining == 72, "quota bucket"); });
Test("missing quota does not become 100 percent", () => { using var doc = JsonDocument.Parse("""{"rateLimits":{"primary":{"windowDurationMins":300}}}"""); bool failed = false; try { AccountUsageClient.Parse(doc.RootElement, origin); } catch (InvalidDataException) { failed = true; } Check(failed, "missing usage"); });
Test("task deep link validates ID", () => { Check(Task("bad/id", Phase.Running).DeepLink == null && Task(Guid.NewGuid().ToString(), Phase.Running).DeepLink?.Scheme == "codex", "URI guard"); });

Console.WriteLine($"{passed} tests passed.");
if (args.Contains("--live"))
{
    var source = new LocalCodexSource(LocalCodexSource.DefaultRoot);
    var snapshot = source.Snapshot([]);
    Console.WriteLine(JsonSerializer.Serialize(new { realLocalRead = true, tasks = snapshot.Tasks.Count, bytesRead = snapshot.BytesRead, states = snapshot.Tasks.GroupBy(t => t.Activity.Phase).ToDictionary(g => g.Key.ToString(), g => g.Count()), warning = snapshot.Warning }));
    var repeat = source.Snapshot([]);
    Console.WriteLine(JsonSerializer.Serialize(new { repeatedReadBytes = repeat.BytesRead }));
    try { var quota = await AccountUsageClient.ReadAsync(source.Root, null, default); Console.WriteLine(JsonSerializer.Serialize(new { realAccountRead = true, windows = quota.Windows.Count, observedAt = quota.ObservedAt })); }
    catch (Exception e) { Console.WriteLine(JsonSerializer.Serialize(new { realAccountRead = false, error = e.GetType().Name, message = e.Message })); Environment.ExitCode = 2; }
}
