plugins { id 'com.android.application' }

android {
    namespace 'com.butang.codextop'
    compileSdk 35
    defaultConfig {
        applicationId 'com.butang.codextop'
        minSdk 30
        targetSdk 35
        versionCode 2
        versionName '1.0.1'
        testInstrumentationRunner 'com.butang.codextop.ContractTest'
    }
    buildFeatures { buildConfig true }
    buildTypes {
        debug { applicationIdSuffix '.debug' }
        release { minifyEnabled false }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    lint { abortOnError true }
}

dependencies { testImplementation 'junit:junit:4.13.2' }
